apiVersion: v1
kind: ConfigMap
metadata:
  name: kubetracer-webhook-config
  namespace: monitoring
data:
  USER_ID: "my-user-id"
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubetracer-webhook
  namespace: monitoring
webhooks:
  - name: kubetracer-webhook.monitoring.svc
    clientConfig:
      service:
        name: kubetracer-webhook-service
        namespace: monitoring
        path: /mutate
      caBundle: CABUNDLE
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-kubetracer-webhook-ca-bundle
  namespace: monitoring
spec:
  template:
    spec:
      containers:
      - name: update-kubetracer-webhook-ca-bundle
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          CA_BUNDLE=$(kubectl get secret root-secret -n cert-manager -o jsonpath='{.data.ca\.crt}' | base64 | tr -d '\n')
          kubectl patch mutatingwebhookconfiguration my-webhook --type='json' -p="[
            {
              \"op\": \"replace\",
              \"path\": \"/webhooks/0/clientConfig/caBundle\",
              \"value\": \"${CA_BUNDLE}\"
            }
          ]"
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
          requests:
            memory: "32Mi"
            cpu: "125m"
      restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetracer-webhook-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetracer-webhook-server
  template:
    metadata:
      labels:
        app: kubetracer-webhook-server
    spec:
      containers:
      - name: kubetracer-webhook-server
        image: localhost:5001/kubetracer-webhook:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: kubetracer-webhook-config
        volumeMounts:
        - name: webhook-certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: kubetracer-webhook-cert-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kubetracer-webhook
  namespace: monitoring
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: kubetracer-webhook-server